# Generated by Django 4.1.3 on 2022-11-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiniCursos',
        ),
    ]
