# Generated by Django 4.1.3 on 2022-11-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_delete_minicursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniCursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
    ]
